#!/bin/bash

# get ubuntu image
curl -sLO https://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64-root.tar.xz

# local
docker build --tag vsv/proot-tests .
docker run -it vsv/proot-tests

# "remote"
heroku create --stack heroku-18 --buildpack https://github.com/niteoweb/heroku-buildpack-shell.git
git push heroku master
